name: Integración a -> Desarrollo
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Usando node.js v15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Actualización de versión
        uses: phips28/gh-action-bump-version@master
