name: Integración a -> Pruebas
on:
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Usando node.js v15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Actualización de versión
        uses: phips28/gh-action-bump-version@master
        with:
          skip-tag: true
      - name: Instalación de dependencias
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - run: npm run build
      - name: Archivar la compilación
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Descargar Compilación
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Desplegando a Firebase -> Pruebas
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy staging --expires 30d --project gamer-quest-co
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
