name: Integraci贸n a -> Pruebas
on:
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Usando node.js v15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Actualizaci贸n de versi贸n
        uses: phips28/gh-action-bump-version@master
        with:
          skip-tag: true
      - name: Instalaci贸n de dependencias
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAMER_QUEST_CO }}'
          channelId: staging
          expires: 30d
          projectId: gamer-quest-co
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
